<template><div><h2 id="自定义移动端长按的hook" tabindex="-1"><a class="header-anchor" href="#自定义移动端长按的hook" aria-hidden="true">#</a> 自定义移动端长按的hook</h2>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">interface</span> <span class="token class-name">ILongPressEventsProps</span> <span class="token punctuation">{</span>
  onLongPressCallback<span class="token operator">:</span> <span class="token punctuation">(</span>
    event<span class="token operator">:</span> React<span class="token punctuation">.</span>TouchEvent<span class="token operator">&lt;</span>HTMLDivElement <span class="token operator">|</span> HTMLTextAreaElement <span class="token operator">|</span> HTMLInputElement<span class="token operator">></span><span class="token punctuation">[</span><span class="token string">'nativeEvent'</span><span class="token punctuation">]</span><span class="token punctuation">[</span><span class="token string">'target'</span><span class="token punctuation">]</span>
  <span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token keyword">void</span><span class="token punctuation">;</span>
  onEndCallback<span class="token operator">?</span><span class="token operator">:</span> <span class="token punctuation">(</span>
    event<span class="token operator">:</span> React<span class="token punctuation">.</span>TouchEvent<span class="token operator">&lt;</span>HTMLDivElement <span class="token operator">|</span> HTMLTextAreaElement <span class="token operator">|</span> HTMLInputElement<span class="token operator">></span><span class="token punctuation">[</span><span class="token string">'nativeEvent'</span><span class="token punctuation">]</span><span class="token punctuation">[</span><span class="token string">'target'</span><span class="token punctuation">]</span>
  <span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token keyword">void</span><span class="token punctuation">;</span>
  delay<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">number</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>

<span class="token keyword">type</span> <span class="token class-name">ILongPressStartMethod</span> <span class="token operator">=</span> <span class="token punctuation">(</span>event<span class="token operator">:</span> React<span class="token punctuation">.</span>TouchEvent<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token keyword">void</span><span class="token punctuation">;</span>
<span class="token keyword">type</span> <span class="token class-name">ILongPressEndMethod</span> <span class="token operator">=</span> <span class="token punctuation">(</span>event<span class="token operator">:</span> React<span class="token punctuation">.</span>TouchEvent<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token keyword">void</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> <span class="token function-variable function">useLongPress</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">{</span> onLongPressCallback<span class="token punctuation">,</span> onEndCallback<span class="token punctuation">,</span> delay <span class="token operator">=</span> <span class="token number">2000</span> <span class="token punctuation">}</span><span class="token operator">:</span> ILongPressEventsProps<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token keyword">let</span> timer<span class="token operator">:</span> <span class="token builtin">any</span> <span class="token operator">=</span> <span class="token keyword">null</span><span class="token punctuation">;</span>
  <span class="token keyword">let</span> target<span class="token operator">:</span> EventTarget <span class="token operator">|</span> <span class="token keyword">null</span><span class="token punctuation">;</span>
  <span class="token keyword">let</span> isStart <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">;</span>
  <span class="token keyword">const</span> start<span class="token operator">:</span> <span class="token function-variable function">ILongPressStartMethod</span> <span class="token operator">=</span> event <span class="token operator">=></span> <span class="token punctuation">{</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span>event<span class="token operator">?.</span>nativeEvent <span class="token keyword">instanceof</span> <span class="token class-name">TouchEvent</span><span class="token punctuation">)</span> target <span class="token operator">=</span> event<span class="token punctuation">.</span>nativeEvent<span class="token punctuation">.</span>target<span class="token punctuation">;</span>
    timer <span class="token operator">=</span> <span class="token function">setTimeout</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
      <span class="token function">onLongPressCallback</span><span class="token punctuation">(</span>target<span class="token punctuation">)</span><span class="token punctuation">;</span>
      isStart <span class="token operator">=</span> <span class="token boolean">true</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span><span class="token punctuation">,</span> delay<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span>isStart<span class="token punctuation">)</span> <span class="token punctuation">{</span>
      event<span class="token punctuation">.</span><span class="token function">stopPropagation</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
      event<span class="token punctuation">.</span><span class="token function">preventDefault</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
  <span class="token punctuation">}</span><span class="token punctuation">;</span>
  <span class="token keyword">const</span> stop<span class="token operator">:</span> <span class="token function-variable function">ILongPressEndMethod</span> <span class="token operator">=</span> event <span class="token operator">=></span> <span class="token punctuation">{</span>
    timer <span class="token operator">&amp;&amp;</span> <span class="token function">clearTimeout</span><span class="token punctuation">(</span>timer<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span>event<span class="token punctuation">.</span>nativeEvent <span class="token keyword">instanceof</span> <span class="token class-name">TouchEvent</span><span class="token punctuation">)</span> target <span class="token operator">=</span> event<span class="token punctuation">.</span>nativeEvent<span class="token punctuation">.</span>target<span class="token punctuation">;</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span>isStart<span class="token punctuation">)</span> <span class="token punctuation">{</span>
      onEndCallback<span class="token operator">?.</span><span class="token punctuation">(</span>target<span class="token punctuation">)</span><span class="token punctuation">;</span>
      event<span class="token punctuation">.</span><span class="token function">stopPropagation</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
      event<span class="token punctuation">.</span><span class="token function">preventDefault</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
      isStart <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
  <span class="token punctuation">}</span><span class="token punctuation">;</span>

  <span class="token keyword">return</span> <span class="token punctuation">{</span>
    onTouchStart<span class="token operator">:</span> start<span class="token punctuation">,</span>
    onTouchMove<span class="token operator">:</span> stop<span class="token punctuation">,</span>
    onTouchEnd<span class="token operator">:</span> stop<span class="token punctuation">,</span>
  <span class="token punctuation">}</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>

</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


